// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function()>()
external void callable_join();

@ffi.Native<ffi.Uint64 Function()>()
external int callable_now_ns();

@ffi.Native<ffi.Bool Function(CallableListener, ffi.Uint64, ffi.Uint64)>()
external bool callable_start(
  CallableListener callback,
  int interval_ns,
  int sample_count,
);

typedef CallableListener =
    ffi.Pointer<ffi.NativeFunction<CallableListenerFunction>>;
typedef CallableListenerFunction = ffi.Void Function(
  ffi.Uint64 timestamp_ns,
  ffi.Uint64 sequence,
);
typedef DartCallableListenerFunction = void Function(
  int timestamp_ns,
  int sequence,
);
