// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int add(int a, int b);

final class Config extends ffi.Struct {
  @ffi.Int()
  external int value;

  @ffi.Int()
  external int is_mac;

  static ffi.Pointer<Config> $allocate(
    ffi.Allocator $allocator, {
    required int value,
    required int is_mac,
  }) => $allocator<Config>()
    ..ref.value = value
    ..ref.is_mac = is_mac;
}
