// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

final class PyConfig extends ffi.Struct {
  @ffi.Int()
  external int _config_init;

  @ffi.Int()
  external int isolated;

  @ffi.Int()
  external int use_environment;

  @ffi.Int()
  external int dev_mode;

  @ffi.Int()
  external int install_signal_handlers;

  @ffi.Int()
  external int use_hash_seed;

  @ffi.UnsignedLong()
  external int hash_seed;

  @ffi.Int()
  external int faulthandler;

  @ffi.Int()
  external int tracemalloc;

  @ffi.Int()
  external int import_time;

  @ffi.Int()
  external int show_ref_count;

  @ffi.Int()
  external int show_alloc_count;

  @ffi.Int()
  external int dump_refs;

  @ffi.Int()
  external int malloc_stats;

  external ffi.Pointer<ffi.WChar> filesystem_encoding;

  external ffi.Pointer<ffi.WChar> filesystem_errors;

  external ffi.Pointer<ffi.WChar> pycache_prefix;

  @ffi.Int()
  external int parse_argv;

  external PyWideStringList argv;

  external ffi.Pointer<ffi.WChar> program_name;

  external PyWideStringList xoptions;

  external PyWideStringList warnoptions;

  @ffi.Int()
  external int site_import;

  @ffi.Int()
  external int bytes_warning;

  @ffi.Int()
  external int inspect;

  @ffi.Int()
  external int interactive;

  @ffi.Int()
  external int optimization_level;

  @ffi.Int()
  external int parser_debug;

  @ffi.Int()
  external int write_bytecode;

  @ffi.Int()
  external int verbose;

  @ffi.Int()
  external int quiet;

  @ffi.Int()
  external int user_site_directory;

  @ffi.Int()
  external int configure_c_stdio;

  @ffi.Int()
  external int buffered_stdio;

  external ffi.Pointer<ffi.WChar> stdio_encoding;

  external ffi.Pointer<ffi.WChar> stdio_errors;

  external ffi.Pointer<ffi.WChar> check_hash_pycs_mode;

  @ffi.Int()
  external int pathconfig_warnings;

  external ffi.Pointer<ffi.WChar> pythonpath_env;

  external ffi.Pointer<ffi.WChar> home;

  @ffi.Int()
  external int module_search_paths_set;

  external PyWideStringList module_search_paths;

  external ffi.Pointer<ffi.WChar> executable;

  external ffi.Pointer<ffi.WChar> base_executable;

  external ffi.Pointer<ffi.WChar> prefix;

  external ffi.Pointer<ffi.WChar> base_prefix;

  external ffi.Pointer<ffi.WChar> exec_prefix;

  external ffi.Pointer<ffi.WChar> base_exec_prefix;

  @ffi.Int()
  external int skip_source_first_line;

  external ffi.Pointer<ffi.WChar> run_command;

  external ffi.Pointer<ffi.WChar> run_module;

  external ffi.Pointer<ffi.WChar> run_filename;

  @ffi.Int()
  external int _install_importlib;

  @ffi.Int()
  external int _init_main;
}

final class PyWideStringList extends ffi.Struct {
  @ffi.Long()
  external int length;

  external ffi.Pointer<ffi.Pointer<ffi.WChar>> items;

  static ffi.Pointer<PyWideStringList> $allocate(
    ffi.Allocator $allocator, {
    required int length,
    required ffi.Pointer<ffi.Pointer<ffi.WChar>> items,
  }) => $allocator<PyWideStringList>()
    ..ref.length = length
    ..ref.items = items;
}
