// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<PyObject> PyBool_FromLong(int arg0) {
    return _PyBool_FromLong(arg0);
  }

  late final _PyBool_FromLongPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function(ffi.Long)>>(
        'PyBool_FromLong',
      );
  late final _PyBool_FromLong =
      _PyBool_FromLongPtr.asFunction<ffi.Pointer<PyObject> Function(int)>();

  void PyErr_Fetch(
    ffi.Pointer<ffi.Pointer<PyObject>> arg0,
    ffi.Pointer<ffi.Pointer<PyObject>> arg1,
    ffi.Pointer<ffi.Pointer<PyObject>> arg2,
  ) {
    return _PyErr_Fetch(arg0, arg1, arg2);
  }

  late final _PyErr_FetchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
          )
        >
      >('PyErr_Fetch');
  late final _PyErr_Fetch =
      _PyErr_FetchPtr.asFunction<
        void Function(
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
        )
      >();

  void PyErr_NormalizeException(
    ffi.Pointer<ffi.Pointer<PyObject>> arg0,
    ffi.Pointer<ffi.Pointer<PyObject>> arg1,
    ffi.Pointer<ffi.Pointer<PyObject>> arg2,
  ) {
    return _PyErr_NormalizeException(arg0, arg1, arg2);
  }

  late final _PyErr_NormalizeExceptionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
          )
        >
      >('PyErr_NormalizeException');
  late final _PyErr_NormalizeException =
      _PyErr_NormalizeExceptionPtr.asFunction<
        void Function(
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
        )
      >();

  ffi.Pointer<PyObject> PyErr_Occurred() {
    return _PyErr_Occurred();
  }

  late final _PyErr_OccurredPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function()>>(
        'PyErr_Occurred',
      );
  late final _PyErr_Occurred =
      _PyErr_OccurredPtr.asFunction<ffi.Pointer<PyObject> Function()>();

  void PyErr_Print() {
    return _PyErr_Print();
  }

  late final _PyErr_PrintPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'PyErr_Print',
  );
  late final _PyErr_Print = _PyErr_PrintPtr.asFunction<void Function()>();

  ffi.Pointer<PyThreadState> PyEval_SaveThread() {
    return _PyEval_SaveThread();
  }

  late final _PyEval_SaveThreadPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyThreadState> Function()>>(
        'PyEval_SaveThread',
      );
  late final _PyEval_SaveThread =
      _PyEval_SaveThreadPtr.asFunction<ffi.Pointer<PyThreadState> Function()>();

  double PyFloat_AsDouble(ffi.Pointer<PyObject> arg0) {
    return _PyFloat_AsDouble(arg0);
  }

  late final _PyFloat_AsDoublePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<PyObject>)>>(
        'PyFloat_AsDouble',
      );
  late final _PyFloat_AsDouble =
      _PyFloat_AsDoublePtr.asFunction<double Function(ffi.Pointer<PyObject>)>();

  ffi.Pointer<PyObject> PyFloat_FromDouble(double arg0) {
    return _PyFloat_FromDouble(arg0);
  }

  late final _PyFloat_FromDoublePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function(ffi.Double)>>(
        'PyFloat_FromDouble',
      );
  late final _PyFloat_FromDouble =
      _PyFloat_FromDoublePtr.asFunction<
        ffi.Pointer<PyObject> Function(double)
      >();

  PyGILState_STATE PyGILState_Ensure() {
    return PyGILState_STATE.fromValue(_PyGILState_Ensure());
  }

  late final _PyGILState_EnsurePtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
        'PyGILState_Ensure',
      );
  late final _PyGILState_Ensure =
      _PyGILState_EnsurePtr.asFunction<int Function()>();

  void PyGILState_Release(PyGILState_STATE arg0) {
    return _PyGILState_Release(arg0.value);
  }

  late final _PyGILState_ReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedInt)>>(
        'PyGILState_Release',
      );
  late final _PyGILState_Release =
      _PyGILState_ReleasePtr.asFunction<void Function(int)>();

  ffi.Pointer<PyObject> PyImport_ImportModule(ffi.Pointer<ffi.Char> name) {
    return _PyImport_ImportModule(name);
  }

  late final _PyImport_ImportModulePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
        >
      >('PyImport_ImportModule');
  late final _PyImport_ImportModule =
      _PyImport_ImportModulePtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
      >();

  int PyLong_AsLong(ffi.Pointer<PyObject> arg0) {
    return _PyLong_AsLong(arg0);
  }

  late final _PyLong_AsLongPtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(ffi.Pointer<PyObject>)>>(
        'PyLong_AsLong',
      );
  late final _PyLong_AsLong =
      _PyLong_AsLongPtr.asFunction<int Function(ffi.Pointer<PyObject>)>();

  ffi.Pointer<PyObject> PyLong_FromLong(int arg0) {
    return _PyLong_FromLong(arg0);
  }

  late final _PyLong_FromLongPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function(ffi.Long)>>(
        'PyLong_FromLong',
      );
  late final _PyLong_FromLong =
      _PyLong_FromLongPtr.asFunction<ffi.Pointer<PyObject> Function(int)>();

  ffi.Pointer<PyObject> PyNumber_Absolute(ffi.Pointer<PyObject> o) {
    return _PyNumber_Absolute(o);
  }

  late final _PyNumber_AbsolutePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyNumber_Absolute');
  late final _PyNumber_Absolute =
      _PyNumber_AbsolutePtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyNumber_Add(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Add(o1, o2);
  }

  late final _PyNumber_AddPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Add');
  late final _PyNumber_Add =
      _PyNumber_AddPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_And(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_And(o1, o2);
  }

  late final _PyNumber_AndPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_And');
  late final _PyNumber_And =
      _PyNumber_AndPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Divmod(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Divmod(o1, o2);
  }

  late final _PyNumber_DivmodPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Divmod');
  late final _PyNumber_Divmod =
      _PyNumber_DivmodPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_FloorDivide(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_FloorDivide(o1, o2);
  }

  late final _PyNumber_FloorDividePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_FloorDivide');
  late final _PyNumber_FloorDivide =
      _PyNumber_FloorDividePtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceAdd(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceAdd(o1, o2);
  }

  late final _PyNumber_InPlaceAddPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceAdd');
  late final _PyNumber_InPlaceAdd =
      _PyNumber_InPlaceAddPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceAnd(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceAnd(o1, o2);
  }

  late final _PyNumber_InPlaceAndPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceAnd');
  late final _PyNumber_InPlaceAnd =
      _PyNumber_InPlaceAndPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceFloorDivide(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceFloorDivide(o1, o2);
  }

  late final _PyNumber_InPlaceFloorDividePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceFloorDivide');
  late final _PyNumber_InPlaceFloorDivide =
      _PyNumber_InPlaceFloorDividePtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceLshift(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceLshift(o1, o2);
  }

  late final _PyNumber_InPlaceLshiftPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceLshift');
  late final _PyNumber_InPlaceLshift =
      _PyNumber_InPlaceLshiftPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceMatrixMultiply(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceMatrixMultiply(o1, o2);
  }

  late final _PyNumber_InPlaceMatrixMultiplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceMatrixMultiply');
  late final _PyNumber_InPlaceMatrixMultiply =
      _PyNumber_InPlaceMatrixMultiplyPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceMultiply(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceMultiply(o1, o2);
  }

  late final _PyNumber_InPlaceMultiplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceMultiply');
  late final _PyNumber_InPlaceMultiply =
      _PyNumber_InPlaceMultiplyPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceOr(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceOr(o1, o2);
  }

  late final _PyNumber_InPlaceOrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceOr');
  late final _PyNumber_InPlaceOr =
      _PyNumber_InPlaceOrPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlacePower(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
    ffi.Pointer<PyObject> o3,
  ) {
    return _PyNumber_InPlacePower(o1, o2, o3);
  }

  late final _PyNumber_InPlacePowerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlacePower');
  late final _PyNumber_InPlacePower =
      _PyNumber_InPlacePowerPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceRemainder(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceRemainder(o1, o2);
  }

  late final _PyNumber_InPlaceRemainderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceRemainder');
  late final _PyNumber_InPlaceRemainder =
      _PyNumber_InPlaceRemainderPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceRshift(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceRshift(o1, o2);
  }

  late final _PyNumber_InPlaceRshiftPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceRshift');
  late final _PyNumber_InPlaceRshift =
      _PyNumber_InPlaceRshiftPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceSubtract(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceSubtract(o1, o2);
  }

  late final _PyNumber_InPlaceSubtractPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceSubtract');
  late final _PyNumber_InPlaceSubtract =
      _PyNumber_InPlaceSubtractPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceTrueDivide(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceTrueDivide(o1, o2);
  }

  late final _PyNumber_InPlaceTrueDividePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceTrueDivide');
  late final _PyNumber_InPlaceTrueDivide =
      _PyNumber_InPlaceTrueDividePtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_InPlaceXor(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_InPlaceXor(o1, o2);
  }

  late final _PyNumber_InPlaceXorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_InPlaceXor');
  late final _PyNumber_InPlaceXor =
      _PyNumber_InPlaceXorPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Invert(ffi.Pointer<PyObject> o) {
    return _PyNumber_Invert(o);
  }

  late final _PyNumber_InvertPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyNumber_Invert');
  late final _PyNumber_Invert =
      _PyNumber_InvertPtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyNumber_Lshift(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Lshift(o1, o2);
  }

  late final _PyNumber_LshiftPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Lshift');
  late final _PyNumber_Lshift =
      _PyNumber_LshiftPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_MatrixMultiply(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_MatrixMultiply(o1, o2);
  }

  late final _PyNumber_MatrixMultiplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_MatrixMultiply');
  late final _PyNumber_MatrixMultiply =
      _PyNumber_MatrixMultiplyPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Multiply(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Multiply(o1, o2);
  }

  late final _PyNumber_MultiplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Multiply');
  late final _PyNumber_Multiply =
      _PyNumber_MultiplyPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Negative(ffi.Pointer<PyObject> o) {
    return _PyNumber_Negative(o);
  }

  late final _PyNumber_NegativePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyNumber_Negative');
  late final _PyNumber_Negative =
      _PyNumber_NegativePtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyNumber_Or(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Or(o1, o2);
  }

  late final _PyNumber_OrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Or');
  late final _PyNumber_Or =
      _PyNumber_OrPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Positive(ffi.Pointer<PyObject> o) {
    return _PyNumber_Positive(o);
  }

  late final _PyNumber_PositivePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyNumber_Positive');
  late final _PyNumber_Positive =
      _PyNumber_PositivePtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyNumber_Power(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
    ffi.Pointer<PyObject> o3,
  ) {
    return _PyNumber_Power(o1, o2, o3);
  }

  late final _PyNumber_PowerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Power');
  late final _PyNumber_Power =
      _PyNumber_PowerPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Remainder(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Remainder(o1, o2);
  }

  late final _PyNumber_RemainderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Remainder');
  late final _PyNumber_Remainder =
      _PyNumber_RemainderPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Rshift(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Rshift(o1, o2);
  }

  late final _PyNumber_RshiftPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Rshift');
  late final _PyNumber_Rshift =
      _PyNumber_RshiftPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Subtract(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Subtract(o1, o2);
  }

  late final _PyNumber_SubtractPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Subtract');
  late final _PyNumber_Subtract =
      _PyNumber_SubtractPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_TrueDivide(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_TrueDivide(o1, o2);
  }

  late final _PyNumber_TrueDividePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_TrueDivide');
  late final _PyNumber_TrueDivide =
      _PyNumber_TrueDividePtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyNumber_Xor(
    ffi.Pointer<PyObject> o1,
    ffi.Pointer<PyObject> o2,
  ) {
    return _PyNumber_Xor(o1, o2);
  }

  late final _PyNumber_XorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyNumber_Xor');
  late final _PyNumber_Xor =
      _PyNumber_XorPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_Call(
    ffi.Pointer<PyObject> callable,
    ffi.Pointer<PyObject> args,
    ffi.Pointer<PyObject> kwargs,
  ) {
    return _PyObject_Call(callable, args, kwargs);
  }

  late final _PyObject_CallPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_Call');
  late final _PyObject_Call =
      _PyObject_CallPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_CallObject(
    ffi.Pointer<PyObject> callable,
    ffi.Pointer<PyObject> args,
  ) {
    return _PyObject_CallObject(callable, args);
  }

  late final _PyObject_CallObjectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_CallObject');
  late final _PyObject_CallObject =
      _PyObject_CallObjectPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  int PyObject_DelItem(ffi.Pointer<PyObject> o, ffi.Pointer<PyObject> key) {
    return _PyObject_DelItem(o, key);
  }

  late final _PyObject_DelItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
        >
      >('PyObject_DelItem');
  late final _PyObject_DelItem =
      _PyObject_DelItemPtr.asFunction<
        int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyObject_GetAttr(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<PyObject> arg1,
  ) {
    return _PyObject_GetAttr(arg0, arg1);
  }

  late final _PyObject_GetAttrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_GetAttr');
  late final _PyObject_GetAttr =
      _PyObject_GetAttrPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_GetAttrString(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<ffi.Char> arg1,
  ) {
    return _PyObject_GetAttrString(arg0, arg1);
  }

  late final _PyObject_GetAttrStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('PyObject_GetAttrString');
  late final _PyObject_GetAttrString =
      _PyObject_GetAttrStringPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_GetItem(
    ffi.Pointer<PyObject> o,
    ffi.Pointer<PyObject> key,
  ) {
    return _PyObject_GetItem(o, key);
  }

  late final _PyObject_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_GetItem');
  late final _PyObject_GetItem =
      _PyObject_GetItemPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  int PyObject_HasAttr(ffi.Pointer<PyObject> arg0, ffi.Pointer<PyObject> arg1) {
    return _PyObject_HasAttr(arg0, arg1);
  }

  late final _PyObject_HasAttrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
        >
      >('PyObject_HasAttr');
  late final _PyObject_HasAttr =
      _PyObject_HasAttrPtr.asFunction<
        int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
      >();

  int PyObject_HasAttrString(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<ffi.Char> arg1,
  ) {
    return _PyObject_HasAttrString(arg0, arg1);
  }

  late final _PyObject_HasAttrStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<PyObject>, ffi.Pointer<ffi.Char>)
        >
      >('PyObject_HasAttrString');
  late final _PyObject_HasAttrString =
      _PyObject_HasAttrStringPtr.asFunction<
        int Function(ffi.Pointer<PyObject>, ffi.Pointer<ffi.Char>)
      >();

  int PyObject_IsInstance(
    ffi.Pointer<PyObject> object,
    ffi.Pointer<PyObject> typeorclass,
  ) {
    return _PyObject_IsInstance(object, typeorclass);
  }

  late final _PyObject_IsInstancePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
        >
      >('PyObject_IsInstance');
  late final _PyObject_IsInstance =
      _PyObject_IsInstancePtr.asFunction<
        int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
      >();

  int PyObject_IsTrue(ffi.Pointer<PyObject> arg0) {
    return _PyObject_IsTrue(arg0);
  }

  late final _PyObject_IsTruePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<PyObject>)>>(
        'PyObject_IsTrue',
      );
  late final _PyObject_IsTrue =
      _PyObject_IsTruePtr.asFunction<int Function(ffi.Pointer<PyObject>)>();

  ffi.Pointer<PyObject> PyObject_Repr(ffi.Pointer<PyObject> arg0) {
    return _PyObject_Repr(arg0);
  }

  late final _PyObject_ReprPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyObject_Repr');
  late final _PyObject_Repr =
      _PyObject_ReprPtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyObject_RichCompare(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<PyObject> arg1,
    int arg2,
  ) {
    return _PyObject_RichCompare(arg0, arg1, arg2);
  }

  late final _PyObject_RichComparePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Int,
          )
        >
      >('PyObject_RichCompare');
  late final _PyObject_RichCompare =
      _PyObject_RichComparePtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          int,
        )
      >();

  int PyObject_RichCompareBool(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<PyObject> arg1,
    int arg2,
  ) {
    return _PyObject_RichCompareBool(arg0, arg1, arg2);
  }

  late final _PyObject_RichCompareBoolPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Int,
          )
        >
      >('PyObject_RichCompareBool');
  late final _PyObject_RichCompareBool =
      _PyObject_RichCompareBoolPtr.asFunction<
        int Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>, int)
      >();

  int PyObject_SetAttr(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<PyObject> arg1,
    ffi.Pointer<PyObject> arg2,
  ) {
    return _PyObject_SetAttr(arg0, arg1, arg2);
  }

  late final _PyObject_SetAttrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_SetAttr');
  late final _PyObject_SetAttr =
      _PyObject_SetAttrPtr.asFunction<
        int Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  int PyObject_SetAttrString(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<ffi.Char> arg1,
    ffi.Pointer<PyObject> arg2,
  ) {
    return _PyObject_SetAttrString(arg0, arg1, arg2);
  }

  late final _PyObject_SetAttrStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_SetAttrString');
  late final _PyObject_SetAttrString =
      _PyObject_SetAttrStringPtr.asFunction<
        int Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<PyObject>,
        )
      >();

  int PyObject_SetItem(
    ffi.Pointer<PyObject> o,
    ffi.Pointer<PyObject> key,
    ffi.Pointer<PyObject> v,
  ) {
    return _PyObject_SetItem(o, key, v);
  }

  late final _PyObject_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_SetItem');
  late final _PyObject_SetItem =
      _PyObject_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_Str(ffi.Pointer<PyObject> arg0) {
    return _PyObject_Str(arg0);
  }

  late final _PyObject_StrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyObject_Str');
  late final _PyObject_Str =
      _PyObject_StrPtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  int PyRun_SimpleString(ffi.Pointer<ffi.Char> s) {
    return _PyRun_SimpleString(s);
  }

  late final _PyRun_SimpleStringPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'PyRun_SimpleString',
      );
  late final _PyRun_SimpleString =
      _PyRun_SimpleStringPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int PyStatus_Exception(PyStatus err) {
    return _PyStatus_Exception(err);
  }

  late final _PyStatus_ExceptionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(PyStatus)>>(
        'PyStatus_Exception',
      );
  late final _PyStatus_Exception =
      _PyStatus_ExceptionPtr.asFunction<int Function(PyStatus)>();

  ffi.Pointer<ffi.Char> PyUnicode_AsUTF8(ffi.Pointer<PyObject> unicode) {
    return _PyUnicode_AsUTF8(unicode);
  }

  late final _PyUnicode_AsUTF8Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<PyObject>)
        >
      >('PyUnicode_AsUTF8');
  late final _PyUnicode_AsUTF8 =
      _PyUnicode_AsUTF8Ptr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyUnicode_FromString(ffi.Pointer<ffi.Char> u) {
    return _PyUnicode_FromString(u);
  }

  late final _PyUnicode_FromStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
        >
      >('PyUnicode_FromString');
  late final _PyUnicode_FromString =
      _PyUnicode_FromStringPtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
      >();

  void Py_DecRef(ffi.Pointer<PyObject> arg0) {
    return _Py_DecRef(arg0);
  }

  late final _Py_DecRefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyObject>)>>(
        'Py_DecRef',
      );
  late final _Py_DecRef =
      _Py_DecRefPtr.asFunction<void Function(ffi.Pointer<PyObject>)>();

  void Py_Finalize() {
    return _Py_Finalize();
  }

  late final _Py_FinalizePtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'Py_Finalize',
  );
  late final _Py_Finalize = _Py_FinalizePtr.asFunction<void Function()>();

  void Py_IncRef(ffi.Pointer<PyObject> arg0) {
    return _Py_IncRef(arg0);
  }

  late final _Py_IncRefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyObject>)>>(
        'Py_IncRef',
      );
  late final _Py_IncRef =
      _Py_IncRefPtr.asFunction<void Function(ffi.Pointer<PyObject>)>();

  int Py_IsInitialized() {
    return _Py_IsInitialized();
  }

  late final _Py_IsInitializedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('Py_IsInitialized');
  late final _Py_IsInitialized =
      _Py_IsInitializedPtr.asFunction<int Function()>();
}

enum PyGILState_STATE {
  PyGILState_LOCKED(0),
  PyGILState_UNLOCKED(1);

  final int value;
  const PyGILState_STATE(this.value);

  static PyGILState_STATE fromValue(int value) => switch (value) {
    0 => PyGILState_LOCKED,
    1 => PyGILState_UNLOCKED,
    _ => throw ArgumentError('Unknown value for PyGILState_STATE: $value'),
  };
}

typedef PyObject = _object;
typedef PyObject$1 = _object;

final class PyStatus extends ffi.Struct {
  @ffi.UnsignedInt()
  external int _type;

  external ffi.Pointer<ffi.Char> func;

  external ffi.Pointer<ffi.Char> err_msg;

  @ffi.Int()
  external int exitcode;

  static ffi.Pointer<PyStatus> $allocate(
    ffi.Allocator $allocator, {
    required int $type,
    required ffi.Pointer<ffi.Char> func,
    required ffi.Pointer<ffi.Char> err_msg,
    required int exitcode,
  }) => $allocator<PyStatus>()
    ..ref._type = $type
    ..ref.func = func
    ..ref.err_msg = err_msg
    ..ref.exitcode = exitcode;
}

typedef PyThreadState = _ts;

final class _object extends ffi.Opaque {}

final class _ts extends ffi.Opaque {}
