// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<PyObject> PyBool_FromLong(int arg0) {
    return _PyBool_FromLong(arg0);
  }

  late final _PyBool_FromLongPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function(ffi.Long)>>(
        'PyBool_FromLong',
      );
  late final _PyBool_FromLong =
      _PyBool_FromLongPtr.asFunction<ffi.Pointer<PyObject> Function(int)>();

  void PyErr_Fetch(
    ffi.Pointer<ffi.Pointer<PyObject>> arg0,
    ffi.Pointer<ffi.Pointer<PyObject>> arg1,
    ffi.Pointer<ffi.Pointer<PyObject>> arg2,
  ) {
    return _PyErr_Fetch(arg0, arg1, arg2);
  }

  late final _PyErr_FetchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
          )
        >
      >('PyErr_Fetch');
  late final _PyErr_Fetch =
      _PyErr_FetchPtr.asFunction<
        void Function(
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
        )
      >();

  void PyErr_NormalizeException(
    ffi.Pointer<ffi.Pointer<PyObject>> arg0,
    ffi.Pointer<ffi.Pointer<PyObject>> arg1,
    ffi.Pointer<ffi.Pointer<PyObject>> arg2,
  ) {
    return _PyErr_NormalizeException(arg0, arg1, arg2);
  }

  late final _PyErr_NormalizeExceptionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
            ffi.Pointer<ffi.Pointer<PyObject>>,
          )
        >
      >('PyErr_NormalizeException');
  late final _PyErr_NormalizeException =
      _PyErr_NormalizeExceptionPtr.asFunction<
        void Function(
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
          ffi.Pointer<ffi.Pointer<PyObject>>,
        )
      >();

  ffi.Pointer<PyObject> PyErr_Occurred() {
    return _PyErr_Occurred();
  }

  late final _PyErr_OccurredPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function()>>(
        'PyErr_Occurred',
      );
  late final _PyErr_Occurred =
      _PyErr_OccurredPtr.asFunction<ffi.Pointer<PyObject> Function()>();

  void PyErr_Print() {
    return _PyErr_Print();
  }

  late final _PyErr_PrintPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'PyErr_Print',
  );
  late final _PyErr_Print = _PyErr_PrintPtr.asFunction<void Function()>();

  double PyFloat_AsDouble(ffi.Pointer<PyObject> arg0) {
    return _PyFloat_AsDouble(arg0);
  }

  late final _PyFloat_AsDoublePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<PyObject>)>>(
        'PyFloat_AsDouble',
      );
  late final _PyFloat_AsDouble =
      _PyFloat_AsDoublePtr.asFunction<double Function(ffi.Pointer<PyObject>)>();

  ffi.Pointer<PyObject> PyFloat_FromDouble(double arg0) {
    return _PyFloat_FromDouble(arg0);
  }

  late final _PyFloat_FromDoublePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function(ffi.Double)>>(
        'PyFloat_FromDouble',
      );
  late final _PyFloat_FromDouble =
      _PyFloat_FromDoublePtr.asFunction<
        ffi.Pointer<PyObject> Function(double)
      >();

  ffi.Pointer<PyObject> PyImport_ImportModule(ffi.Pointer<ffi.Char> name) {
    return _PyImport_ImportModule(name);
  }

  late final _PyImport_ImportModulePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
        >
      >('PyImport_ImportModule');
  late final _PyImport_ImportModule =
      _PyImport_ImportModulePtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
      >();

  int PyLong_AsLong(ffi.Pointer<PyObject> arg0) {
    return _PyLong_AsLong(arg0);
  }

  late final _PyLong_AsLongPtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(ffi.Pointer<PyObject>)>>(
        'PyLong_AsLong',
      );
  late final _PyLong_AsLong =
      _PyLong_AsLongPtr.asFunction<int Function(ffi.Pointer<PyObject>)>();

  ffi.Pointer<PyObject> PyLong_FromLong(int arg0) {
    return _PyLong_FromLong(arg0);
  }

  late final _PyLong_FromLongPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PyObject> Function(ffi.Long)>>(
        'PyLong_FromLong',
      );
  late final _PyLong_FromLong =
      _PyLong_FromLongPtr.asFunction<ffi.Pointer<PyObject> Function(int)>();

  ffi.Pointer<PyObject> PyObject_Call(
    ffi.Pointer<PyObject> callable,
    ffi.Pointer<PyObject> args,
    ffi.Pointer<PyObject> kwargs,
  ) {
    return _PyObject_Call(callable, args, kwargs);
  }

  late final _PyObject_CallPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_Call');
  late final _PyObject_Call =
      _PyObject_CallPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_CallObject(
    ffi.Pointer<PyObject> callable,
    ffi.Pointer<PyObject> args,
  ) {
    return _PyObject_CallObject(callable, args);
  }

  late final _PyObject_CallObjectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_CallObject');
  late final _PyObject_CallObject =
      _PyObject_CallObjectPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_GetAttrString(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<ffi.Char> arg1,
  ) {
    return _PyObject_GetAttrString(arg0, arg1);
  }

  late final _PyObject_GetAttrStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('PyObject_GetAttrString');
  late final _PyObject_GetAttrString =
      _PyObject_GetAttrStringPtr.asFunction<
        ffi.Pointer<PyObject> Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int PyObject_HasAttrString(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<ffi.Char> arg1,
  ) {
    return _PyObject_HasAttrString(arg0, arg1);
  }

  late final _PyObject_HasAttrStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<PyObject>, ffi.Pointer<ffi.Char>)
        >
      >('PyObject_HasAttrString');
  late final _PyObject_HasAttrString =
      _PyObject_HasAttrStringPtr.asFunction<
        int Function(ffi.Pointer<PyObject>, ffi.Pointer<ffi.Char>)
      >();

  int PyObject_IsTrue(ffi.Pointer<PyObject> arg0) {
    return _PyObject_IsTrue(arg0);
  }

  late final _PyObject_IsTruePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<PyObject>)>>(
        'PyObject_IsTrue',
      );
  late final _PyObject_IsTrue =
      _PyObject_IsTruePtr.asFunction<int Function(ffi.Pointer<PyObject>)>();

  int PyObject_SetAttrString(
    ffi.Pointer<PyObject> arg0,
    ffi.Pointer<ffi.Char> arg1,
    ffi.Pointer<PyObject> arg2,
  ) {
    return _PyObject_SetAttrString(arg0, arg1, arg2);
  }

  late final _PyObject_SetAttrStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PyObject>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<PyObject>,
          )
        >
      >('PyObject_SetAttrString');
  late final _PyObject_SetAttrString =
      _PyObject_SetAttrStringPtr.asFunction<
        int Function(
          ffi.Pointer<PyObject>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<PyObject>,
        )
      >();

  ffi.Pointer<PyObject> PyObject_Str(ffi.Pointer<PyObject> arg0) {
    return _PyObject_Str(arg0);
  }

  late final _PyObject_StrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
        >
      >('PyObject_Str');
  late final _PyObject_Str =
      _PyObject_StrPtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)
      >();

  int PyRun_SimpleString(ffi.Pointer<ffi.Char> s) {
    return _PyRun_SimpleString(s);
  }

  late final _PyRun_SimpleStringPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'PyRun_SimpleString',
      );
  late final _PyRun_SimpleString =
      _PyRun_SimpleStringPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int PyStatus_Exception(PyStatus err) {
    return _PyStatus_Exception(err);
  }

  late final _PyStatus_ExceptionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(PyStatus)>>(
        'PyStatus_Exception',
      );
  late final _PyStatus_Exception =
      _PyStatus_ExceptionPtr.asFunction<int Function(PyStatus)>();

  ffi.Pointer<ffi.Char> PyUnicode_AsUTF8(ffi.Pointer<PyObject> unicode) {
    return _PyUnicode_AsUTF8(unicode);
  }

  late final _PyUnicode_AsUTF8Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<PyObject>)
        >
      >('PyUnicode_AsUTF8');
  late final _PyUnicode_AsUTF8 =
      _PyUnicode_AsUTF8Ptr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<PyObject>)
      >();

  ffi.Pointer<PyObject> PyUnicode_FromString(ffi.Pointer<ffi.Char> u) {
    return _PyUnicode_FromString(u);
  }

  late final _PyUnicode_FromStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
        >
      >('PyUnicode_FromString');
  late final _PyUnicode_FromString =
      _PyUnicode_FromStringPtr.asFunction<
        ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)
      >();

  void Py_DecRef(ffi.Pointer<PyObject> arg0) {
    return _Py_DecRef(arg0);
  }

  late final _Py_DecRefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyObject>)>>(
        'Py_DecRef',
      );
  late final _Py_DecRef =
      _Py_DecRefPtr.asFunction<void Function(ffi.Pointer<PyObject>)>();

  void Py_Finalize() {
    return _Py_Finalize();
  }

  late final _Py_FinalizePtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'Py_Finalize',
  );
  late final _Py_Finalize = _Py_FinalizePtr.asFunction<void Function()>();

  void Py_IncRef(ffi.Pointer<PyObject> arg0) {
    return _Py_IncRef(arg0);
  }

  late final _Py_IncRefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyObject>)>>(
        'Py_IncRef',
      );
  late final _Py_IncRef =
      _Py_IncRefPtr.asFunction<void Function(ffi.Pointer<PyObject>)>();
}

typedef PyObject = _object;
typedef PyObject$1 = _object;

final class PyStatus extends ffi.Struct {
  @ffi.UnsignedInt()
  external int _type;

  external ffi.Pointer<ffi.Char> func;

  external ffi.Pointer<ffi.Char> err_msg;

  @ffi.Int()
  external int exitcode;

  static ffi.Pointer<PyStatus> $allocate(
    ffi.Allocator $allocator, {
    required int $type,
    required ffi.Pointer<ffi.Char> func,
    required ffi.Pointer<ffi.Char> err_msg,
    required int exitcode,
  }) => $allocator<PyStatus>()
    ..ref._type = $type
    ..ref.func = func
    ..ref.err_msg = err_msg
    ..ref.exitcode = exitcode;
}

final class _object extends ffi.Opaque {}
