// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int PyRun_SimpleString(ffi.Pointer<ffi.Char> s) {
    return _PyRun_SimpleString(s);
  }

  late final _PyRun_SimpleStringPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'PyRun_SimpleString',
      );
  late final _PyRun_SimpleString =
      _PyRun_SimpleStringPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int PyStatus_Exception(PyStatus err) {
    return _PyStatus_Exception(err);
  }

  late final _PyStatus_ExceptionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(PyStatus)>>(
        'PyStatus_Exception',
      );
  late final _PyStatus_Exception =
      _PyStatus_ExceptionPtr.asFunction<int Function(PyStatus)>();

  void Py_Finalize() {
    return _Py_Finalize();
  }

  late final _Py_FinalizePtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'Py_Finalize',
  );
  late final _Py_Finalize = _Py_FinalizePtr.asFunction<void Function()>();
}

typedef PyObject = _object;

final class PyStatus extends ffi.Struct {
  @ffi.UnsignedInt()
  external int _type;

  external ffi.Pointer<ffi.Char> func;

  external ffi.Pointer<ffi.Char> err_msg;

  @ffi.Int()
  external int exitcode;

  static ffi.Pointer<PyStatus> $allocate(
    ffi.Allocator $allocator, {
    required int $type,
    required ffi.Pointer<ffi.Char> func,
    required ffi.Pointer<ffi.Char> err_msg,
    required int exitcode,
  }) => $allocator<PyStatus>()
    ..ref._type = $type
    ..ref.func = func
    ..ref.err_msg = err_msg
    ..ref.exitcode = exitcode;
}

final class _object extends ffi.Opaque {}
