// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

import 'shared.g.dart' as imp$1;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void PyConfig_Clear(ffi.Pointer<PyConfig> arg0) {
    return _PyConfig_Clear(arg0);
  }

  late final _PyConfig_ClearPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyConfig>)>>(
        'PyConfig_Clear',
      );
  late final _PyConfig_Clear =
      _PyConfig_ClearPtr.asFunction<void Function(ffi.Pointer<PyConfig>)>();

  void PyConfig_InitPythonConfig(ffi.Pointer<PyConfig> config) {
    return _PyConfig_InitPythonConfig(config);
  }

  late final _PyConfig_InitPythonConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyConfig>)>>(
        'PyConfig_InitPythonConfig',
      );
  late final _PyConfig_InitPythonConfig =
      _PyConfig_InitPythonConfigPtr.asFunction<
        void Function(ffi.Pointer<PyConfig>)
      >();

  imp$1.PyStatus PyConfig_SetString(
    ffi.Pointer<PyConfig> config,
    ffi.Pointer<ffi.Pointer<ffi.WChar>> config_str,
    ffi.Pointer<ffi.WChar> str,
  ) {
    return _PyConfig_SetString(config, config_str, str);
  }

  late final _PyConfig_SetStringPtr =
      _lookup<
        ffi.NativeFunction<
          imp$1.PyStatus Function(
            ffi.Pointer<PyConfig>,
            ffi.Pointer<ffi.Pointer<ffi.WChar>>,
            ffi.Pointer<ffi.WChar>,
          )
        >
      >('PyConfig_SetString');
  late final _PyConfig_SetString =
      _PyConfig_SetStringPtr.asFunction<
        imp$1.PyStatus Function(
          ffi.Pointer<PyConfig>,
          ffi.Pointer<ffi.Pointer<ffi.WChar>>,
          ffi.Pointer<ffi.WChar>,
        )
      >();

  void PyDict_Clear(ffi.Pointer<imp$1.PyObject> mp) {
    return _PyDict_Clear(mp);
  }

  late final _PyDict_ClearPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyDict_Clear');
  late final _PyDict_Clear =
      _PyDict_ClearPtr.asFunction<void Function(ffi.Pointer<imp$1.PyObject>)>();

  int PyDict_Contains(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<imp$1.PyObject> key,
  ) {
    return _PyDict_Contains(mp, key);
  }

  late final _PyDict_ContainsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyDict_Contains');
  late final _PyDict_Contains =
      _PyDict_ContainsPtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>, ffi.Pointer<imp$1.PyObject>)
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_Copy(ffi.Pointer<imp$1.PyObject> mp) {
    return _PyDict_Copy(mp);
  }

  late final _PyDict_CopyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
        >
      >('PyDict_Copy');
  late final _PyDict_Copy =
      _PyDict_CopyPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
      >();

  int PyDict_DelItem(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<imp$1.PyObject> key,
  ) {
    return _PyDict_DelItem(mp, key);
  }

  late final _PyDict_DelItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyDict_DelItem');
  late final _PyDict_DelItem =
      _PyDict_DelItemPtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>, ffi.Pointer<imp$1.PyObject>)
      >();

  int PyDict_DelItemString(
    ffi.Pointer<imp$1.PyObject> dp,
    ffi.Pointer<ffi.Char> key,
  ) {
    return _PyDict_DelItemString(dp, key);
  }

  late final _PyDict_DelItemStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<imp$1.PyObject>, ffi.Pointer<ffi.Char>)
        >
      >('PyDict_DelItemString');
  late final _PyDict_DelItemString =
      _PyDict_DelItemStringPtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>, ffi.Pointer<ffi.Char>)
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_GetItem(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<imp$1.PyObject> key,
  ) {
    return _PyDict_GetItem(mp, key);
  }

  late final _PyDict_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyDict_GetItem');
  late final _PyDict_GetItem =
      _PyDict_GetItemPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_GetItemString(
    ffi.Pointer<imp$1.PyObject> dp,
    ffi.Pointer<ffi.Char> key,
  ) {
    return _PyDict_GetItemString(dp, key);
  }

  late final _PyDict_GetItemStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('PyDict_GetItemString');
  late final _PyDict_GetItemString =
      _PyDict_GetItemStringPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_Items(ffi.Pointer<imp$1.PyObject> mp) {
    return _PyDict_Items(mp);
  }

  late final _PyDict_ItemsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
        >
      >('PyDict_Items');
  late final _PyDict_Items =
      _PyDict_ItemsPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_Keys(ffi.Pointer<imp$1.PyObject> mp) {
    return _PyDict_Keys(mp);
  }

  late final _PyDict_KeysPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
        >
      >('PyDict_Keys');
  late final _PyDict_Keys =
      _PyDict_KeysPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
      >();

  int PyDict_Merge(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<imp$1.PyObject> other,
    int override,
  ) {
    return _PyDict_Merge(mp, other, override);
  }

  late final _PyDict_MergePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
            ffi.Int,
          )
        >
      >('PyDict_Merge');
  late final _PyDict_Merge =
      _PyDict_MergePtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<imp$1.PyObject>,
          int,
        )
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_New() {
    return _PyDict_New();
  }

  late final _PyDict_NewPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<imp$1.PyObject> Function()>>(
        'PyDict_New',
      );
  late final _PyDict_New =
      _PyDict_NewPtr.asFunction<ffi.Pointer<imp$1.PyObject> Function()>();

  int PyDict_Next(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<Py_ssize_t> pos,
    ffi.Pointer<ffi.Pointer<imp$1.PyObject>> key,
    ffi.Pointer<ffi.Pointer<imp$1.PyObject>> value,
  ) {
    return _PyDict_Next(mp, pos, key, value);
  }

  late final _PyDict_NextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<Py_ssize_t>,
            ffi.Pointer<ffi.Pointer<imp$1.PyObject>>,
            ffi.Pointer<ffi.Pointer<imp$1.PyObject>>,
          )
        >
      >('PyDict_Next');
  late final _PyDict_Next =
      _PyDict_NextPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<Py_ssize_t>,
          ffi.Pointer<ffi.Pointer<imp$1.PyObject>>,
          ffi.Pointer<ffi.Pointer<imp$1.PyObject>>,
        )
      >();

  int PyDict_SetItem(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<imp$1.PyObject> key,
    ffi.Pointer<imp$1.PyObject> item,
  ) {
    return _PyDict_SetItem(mp, key, item);
  }

  late final _PyDict_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyDict_SetItem');
  late final _PyDict_SetItem =
      _PyDict_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  int PyDict_SetItemString(
    ffi.Pointer<imp$1.PyObject> dp,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<imp$1.PyObject> item,
  ) {
    return _PyDict_SetItemString(dp, key, item);
  }

  late final _PyDict_SetItemStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyDict_SetItemString');
  late final _PyDict_SetItemString =
      _PyDict_SetItemStringPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  int PyDict_Size(ffi.Pointer<imp$1.PyObject> mp) {
    return _PyDict_Size(mp);
  }

  late final _PyDict_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyDict_Size');
  late final _PyDict_Size =
      _PyDict_SizePtr.asFunction<int Function(ffi.Pointer<imp$1.PyObject>)>();

  int PyDict_Update(
    ffi.Pointer<imp$1.PyObject> mp,
    ffi.Pointer<imp$1.PyObject> other,
  ) {
    return _PyDict_Update(mp, other);
  }

  late final _PyDict_UpdatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyDict_Update');
  late final _PyDict_Update =
      _PyDict_UpdatePtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>, ffi.Pointer<imp$1.PyObject>)
      >();

  ffi.Pointer<imp$1.PyObject> PyDict_Values(ffi.Pointer<imp$1.PyObject> mp) {
    return _PyDict_Values(mp);
  }

  late final _PyDict_ValuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
        >
      >('PyDict_Values');
  late final _PyDict_Values =
      _PyDict_ValuesPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>)
      >();

  int PyList_Append(
    ffi.Pointer<imp$1.PyObject> arg0,
    ffi.Pointer<imp$1.PyObject> arg1,
  ) {
    return _PyList_Append(arg0, arg1);
  }

  late final _PyList_AppendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyList_Append');
  late final _PyList_Append =
      _PyList_AppendPtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>, ffi.Pointer<imp$1.PyObject>)
      >();

  ffi.Pointer<imp$1.PyObject> PyList_GetItem(
    ffi.Pointer<imp$1.PyObject> arg0,
    int arg1,
  ) {
    return _PyList_GetItem(arg0, arg1);
  }

  late final _PyList_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
          )
        >
      >('PyList_GetItem');
  late final _PyList_GetItem =
      _PyList_GetItemPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>, int)
      >();

  int PyList_Insert(
    ffi.Pointer<imp$1.PyObject> arg0,
    int arg1,
    ffi.Pointer<imp$1.PyObject> arg2,
  ) {
    return _PyList_Insert(arg0, arg1, arg2);
  }

  late final _PyList_InsertPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyList_Insert');
  late final _PyList_Insert =
      _PyList_InsertPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          int,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  ffi.Pointer<imp$1.PyObject> PyList_New(int size) {
    return _PyList_New(size);
  }

  late final _PyList_NewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<imp$1.PyObject> Function(Py_ssize_t)>
      >('PyList_New');
  late final _PyList_New =
      _PyList_NewPtr.asFunction<ffi.Pointer<imp$1.PyObject> Function(int)>();

  int PyList_Reverse(ffi.Pointer<imp$1.PyObject> arg0) {
    return _PyList_Reverse(arg0);
  }

  late final _PyList_ReversePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyList_Reverse');
  late final _PyList_Reverse =
      _PyList_ReversePtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>)
      >();

  int PyList_SetItem(
    ffi.Pointer<imp$1.PyObject> arg0,
    int arg1,
    ffi.Pointer<imp$1.PyObject> arg2,
  ) {
    return _PyList_SetItem(arg0, arg1, arg2);
  }

  late final _PyList_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyList_SetItem');
  late final _PyList_SetItem =
      _PyList_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          int,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  int PyList_Size(ffi.Pointer<imp$1.PyObject> arg0) {
    return _PyList_Size(arg0);
  }

  late final _PyList_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyList_Size');
  late final _PyList_Size =
      _PyList_SizePtr.asFunction<int Function(ffi.Pointer<imp$1.PyObject>)>();

  int PyList_Sort(ffi.Pointer<imp$1.PyObject> arg0) {
    return _PyList_Sort(arg0);
  }

  late final _PyList_SortPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyList_Sort');
  late final _PyList_Sort =
      _PyList_SortPtr.asFunction<int Function(ffi.Pointer<imp$1.PyObject>)>();

  ffi.Pointer<imp$1.PyObject> PySequence_Concat(
    ffi.Pointer<imp$1.PyObject> o1,
    ffi.Pointer<imp$1.PyObject> o2,
  ) {
    return _PySequence_Concat(o1, o2);
  }

  late final _PySequence_ConcatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PySequence_Concat');
  late final _PySequence_Concat =
      _PySequence_ConcatPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(
          ffi.Pointer<imp$1.PyObject>,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  int PySequence_DelItem(ffi.Pointer<imp$1.PyObject> o, int i) {
    return _PySequence_DelItem(o, i);
  }

  late final _PySequence_DelItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<imp$1.PyObject>, Py_ssize_t)
        >
      >('PySequence_DelItem');
  late final _PySequence_DelItem =
      _PySequence_DelItemPtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>, int)
      >();

  ffi.Pointer<imp$1.PyObject> PySequence_GetItem(
    ffi.Pointer<imp$1.PyObject> o,
    int i,
  ) {
    return _PySequence_GetItem(o, i);
  }

  late final _PySequence_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
          )
        >
      >('PySequence_GetItem');
  late final _PySequence_GetItem =
      _PySequence_GetItemPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>, int)
      >();

  ffi.Pointer<imp$1.PyObject> PySequence_Repeat(
    ffi.Pointer<imp$1.PyObject> o,
    int count,
  ) {
    return _PySequence_Repeat(o, count);
  }

  late final _PySequence_RepeatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
          )
        >
      >('PySequence_Repeat');
  late final _PySequence_Repeat =
      _PySequence_RepeatPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>, int)
      >();

  int PySequence_SetItem(
    ffi.Pointer<imp$1.PyObject> o,
    int i,
    ffi.Pointer<imp$1.PyObject> v,
  ) {
    return _PySequence_SetItem(o, i, v);
  }

  late final _PySequence_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PySequence_SetItem');
  late final _PySequence_SetItem =
      _PySequence_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          int,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  int PyObject_Size(ffi.Pointer<imp$1.PyObject> o) {
    return _PyObject_Size(o);
  }

  late final _PyObject_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyObject_Size');
  late final _PyObject_Size =
      _PyObject_SizePtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>)
      >();

  int PySequence_Size(ffi.Pointer<imp$1.PyObject> o) {
    return _PySequence_Size(o);
  }

  late final _PySequence_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject>)>
      >('PySequence_Size');
  late final _PySequence_Size =
      _PySequence_SizePtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject>)
      >();

  ffi.Pointer<imp$1.PyObject> PyTuple_GetItem(
    ffi.Pointer<imp$1.PyObject> arg0,
    int arg1,
  ) {
    return _PyTuple_GetItem(arg0, arg1);
  }

  late final _PyTuple_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject> Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
          )
        >
      >('PyTuple_GetItem');
  late final _PyTuple_GetItem =
      _PyTuple_GetItemPtr.asFunction<
        ffi.Pointer<imp$1.PyObject> Function(ffi.Pointer<imp$1.PyObject>, int)
      >();

  ffi.Pointer<imp$1.PyObject> PyTuple_New(int size) {
    return _PyTuple_New(size);
  }

  late final _PyTuple_NewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<imp$1.PyObject> Function(Py_ssize_t)>
      >('PyTuple_New');
  late final _PyTuple_New =
      _PyTuple_NewPtr.asFunction<ffi.Pointer<imp$1.PyObject> Function(int)>();

  int PyTuple_SetItem(
    ffi.Pointer<imp$1.PyObject> arg0,
    int arg1,
    ffi.Pointer<imp$1.PyObject> arg2,
  ) {
    return _PyTuple_SetItem(arg0, arg1, arg2);
  }

  late final _PyTuple_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject>,
          )
        >
      >('PyTuple_SetItem');
  late final _PyTuple_SetItem =
      _PyTuple_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject>,
          int,
          ffi.Pointer<imp$1.PyObject>,
        )
      >();

  int PyTuple_Size(ffi.Pointer<imp$1.PyObject> arg0) {
    return _PyTuple_Size(arg0);
  }

  late final _PyTuple_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject>)>
      >('PyTuple_Size');
  late final _PyTuple_Size =
      _PyTuple_SizePtr.asFunction<int Function(ffi.Pointer<imp$1.PyObject>)>();

  imp$1.PyStatus Py_InitializeFromConfig(ffi.Pointer<PyConfig> config) {
    return _Py_InitializeFromConfig(config);
  }

  late final _Py_InitializeFromConfigPtr =
      _lookup<
        ffi.NativeFunction<imp$1.PyStatus Function(ffi.Pointer<PyConfig>)>
      >('Py_InitializeFromConfig');
  late final _Py_InitializeFromConfig =
      _Py_InitializeFromConfigPtr.asFunction<
        imp$1.PyStatus Function(ffi.Pointer<PyConfig>)
      >();
}

final class PyConfig extends ffi.Struct {
  @ffi.Int()
  external int _config_init;

  @ffi.Int()
  external int isolated;

  @ffi.Int()
  external int use_environment;

  @ffi.Int()
  external int dev_mode;

  @ffi.Int()
  external int install_signal_handlers;

  @ffi.Int()
  external int use_hash_seed;

  @ffi.UnsignedLong()
  external int hash_seed;

  @ffi.Int()
  external int faulthandler;

  @ffi.Int()
  external int tracemalloc;

  @ffi.Int()
  external int import_time;

  @ffi.Int()
  external int code_debug_ranges;

  @ffi.Int()
  external int show_ref_count;

  @ffi.Int()
  external int dump_refs;

  external ffi.Pointer<ffi.WChar> dump_refs_file;

  @ffi.Int()
  external int malloc_stats;

  external ffi.Pointer<ffi.WChar> filesystem_encoding;

  external ffi.Pointer<ffi.WChar> filesystem_errors;

  external ffi.Pointer<ffi.WChar> pycache_prefix;

  @ffi.Int()
  external int parse_argv;

  external PyWideStringList orig_argv;

  external PyWideStringList argv;

  external PyWideStringList xoptions;

  external PyWideStringList warnoptions;

  @ffi.Int()
  external int site_import;

  @ffi.Int()
  external int bytes_warning;

  @ffi.Int()
  external int warn_default_encoding;

  @ffi.Int()
  external int inspect;

  @ffi.Int()
  external int interactive;

  @ffi.Int()
  external int optimization_level;

  @ffi.Int()
  external int parser_debug;

  @ffi.Int()
  external int write_bytecode;

  @ffi.Int()
  external int verbose;

  @ffi.Int()
  external int quiet;

  @ffi.Int()
  external int user_site_directory;

  @ffi.Int()
  external int configure_c_stdio;

  @ffi.Int()
  external int buffered_stdio;

  external ffi.Pointer<ffi.WChar> stdio_encoding;

  external ffi.Pointer<ffi.WChar> stdio_errors;

  @ffi.Int()
  external int legacy_windows_stdio;

  external ffi.Pointer<ffi.WChar> check_hash_pycs_mode;

  @ffi.Int()
  external int use_frozen_modules;

  @ffi.Int()
  external int safe_path;

  @ffi.Int()
  external int pathconfig_warnings;

  external ffi.Pointer<ffi.WChar> program_name;

  external ffi.Pointer<ffi.WChar> pythonpath_env;

  external ffi.Pointer<ffi.WChar> home;

  external ffi.Pointer<ffi.WChar> platlibdir;

  @ffi.Int()
  external int module_search_paths_set;

  external PyWideStringList module_search_paths;

  external ffi.Pointer<ffi.WChar> stdlib_dir;

  external ffi.Pointer<ffi.WChar> executable;

  external ffi.Pointer<ffi.WChar> base_executable;

  external ffi.Pointer<ffi.WChar> prefix;

  external ffi.Pointer<ffi.WChar> base_prefix;

  external ffi.Pointer<ffi.WChar> exec_prefix;

  external ffi.Pointer<ffi.WChar> base_exec_prefix;

  @ffi.Int()
  external int skip_source_first_line;

  external ffi.Pointer<ffi.WChar> run_command;

  external ffi.Pointer<ffi.WChar> run_module;

  external ffi.Pointer<ffi.WChar> run_filename;

  @ffi.Int()
  external int _install_importlib;

  @ffi.Int()
  external int _init_main;

  @ffi.Int()
  external int _isolated_interpreter;

  @ffi.Int()
  external int _is_python_build;
}

final class PyWideStringList extends ffi.Struct {
  @Py_ssize_t()
  external int length;

  external ffi.Pointer<ffi.Pointer<ffi.WChar>> items;

  static ffi.Pointer<PyWideStringList> $allocate(
    ffi.Allocator $allocator, {
    required int length,
    required ffi.Pointer<ffi.Pointer<ffi.WChar>> items,
  }) => $allocator<PyWideStringList>()
    ..ref.length = length
    ..ref.items = items;
}

typedef Py_ssize_t = ffi.LongLong;
typedef DartPy_ssize_t = int;
