// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

import 'shared.g.dart' as imp$1;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void PyConfig_Clear(ffi.Pointer<PyConfig> arg0) {
    return _PyConfig_Clear(arg0);
  }

  late final _PyConfig_ClearPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyConfig>)>>(
        'PyConfig_Clear',
      );
  late final _PyConfig_Clear =
      _PyConfig_ClearPtr.asFunction<void Function(ffi.Pointer<PyConfig>)>();

  void PyConfig_InitPythonConfig(ffi.Pointer<PyConfig> config) {
    return _PyConfig_InitPythonConfig(config);
  }

  late final _PyConfig_InitPythonConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PyConfig>)>>(
        'PyConfig_InitPythonConfig',
      );
  late final _PyConfig_InitPythonConfig =
      _PyConfig_InitPythonConfigPtr.asFunction<
        void Function(ffi.Pointer<PyConfig>)
      >();

  imp$1.PyStatus PyConfig_SetString(
    ffi.Pointer<PyConfig> config,
    ffi.Pointer<ffi.Pointer<ffi.WChar>> config_str,
    ffi.Pointer<ffi.WChar> str,
  ) {
    return _PyConfig_SetString(config, config_str, str);
  }

  late final _PyConfig_SetStringPtr =
      _lookup<
        ffi.NativeFunction<
          imp$1.PyStatus Function(
            ffi.Pointer<PyConfig>,
            ffi.Pointer<ffi.Pointer<ffi.WChar>>,
            ffi.Pointer<ffi.WChar>,
          )
        >
      >('PyConfig_SetString');
  late final _PyConfig_SetString =
      _PyConfig_SetStringPtr.asFunction<
        imp$1.PyStatus Function(
          ffi.Pointer<PyConfig>,
          ffi.Pointer<ffi.Pointer<ffi.WChar>>,
          ffi.Pointer<ffi.WChar>,
        )
      >();

  int PyList_Append(
    ffi.Pointer<imp$1.PyObject$1> arg0,
    ffi.Pointer<imp$1.PyObject$1> arg1,
  ) {
    return _PyList_Append(arg0, arg1);
  }

  late final _PyList_AppendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject$1>,
            ffi.Pointer<imp$1.PyObject$1>,
          )
        >
      >('PyList_Append');
  late final _PyList_Append =
      _PyList_AppendPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject$1>,
          ffi.Pointer<imp$1.PyObject$1>,
        )
      >();

  ffi.Pointer<imp$1.PyObject$1> PyList_GetItem(
    ffi.Pointer<imp$1.PyObject$1> arg0,
    int arg1,
  ) {
    return _PyList_GetItem(arg0, arg1);
  }

  late final _PyList_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject$1> Function(
            ffi.Pointer<imp$1.PyObject$1>,
            Py_ssize_t,
          )
        >
      >('PyList_GetItem');
  late final _PyList_GetItem =
      _PyList_GetItemPtr.asFunction<
        ffi.Pointer<imp$1.PyObject$1> Function(
          ffi.Pointer<imp$1.PyObject$1>,
          int,
        )
      >();

  int PyList_Insert(
    ffi.Pointer<imp$1.PyObject$1> arg0,
    int arg1,
    ffi.Pointer<imp$1.PyObject$1> arg2,
  ) {
    return _PyList_Insert(arg0, arg1, arg2);
  }

  late final _PyList_InsertPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject$1>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject$1>,
          )
        >
      >('PyList_Insert');
  late final _PyList_Insert =
      _PyList_InsertPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject$1>,
          int,
          ffi.Pointer<imp$1.PyObject$1>,
        )
      >();

  ffi.Pointer<imp$1.PyObject$1> PyList_New(int size) {
    return _PyList_New(size);
  }

  late final _PyList_NewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<imp$1.PyObject$1> Function(Py_ssize_t)>
      >('PyList_New');
  late final _PyList_New =
      _PyList_NewPtr.asFunction<ffi.Pointer<imp$1.PyObject$1> Function(int)>();

  int PyList_Reverse(ffi.Pointer<imp$1.PyObject$1> arg0) {
    return _PyList_Reverse(arg0);
  }

  late final _PyList_ReversePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<imp$1.PyObject$1>)>
      >('PyList_Reverse');
  late final _PyList_Reverse =
      _PyList_ReversePtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject$1>)
      >();

  int PyList_SetItem(
    ffi.Pointer<imp$1.PyObject$1> arg0,
    int arg1,
    ffi.Pointer<imp$1.PyObject$1> arg2,
  ) {
    return _PyList_SetItem(arg0, arg1, arg2);
  }

  late final _PyList_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject$1>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject$1>,
          )
        >
      >('PyList_SetItem');
  late final _PyList_SetItem =
      _PyList_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject$1>,
          int,
          ffi.Pointer<imp$1.PyObject$1>,
        )
      >();

  int PyList_Size(ffi.Pointer<imp$1.PyObject$1> arg0) {
    return _PyList_Size(arg0);
  }

  late final _PyList_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject$1>)>
      >('PyList_Size');
  late final _PyList_Size =
      _PyList_SizePtr.asFunction<int Function(ffi.Pointer<imp$1.PyObject$1>)>();

  int PyList_Sort(ffi.Pointer<imp$1.PyObject$1> arg0) {
    return _PyList_Sort(arg0);
  }

  late final _PyList_SortPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<imp$1.PyObject$1>)>
      >('PyList_Sort');
  late final _PyList_Sort =
      _PyList_SortPtr.asFunction<int Function(ffi.Pointer<imp$1.PyObject$1>)>();

  ffi.Pointer<imp$1.PyObject$1> PyTuple_GetItem(
    ffi.Pointer<imp$1.PyObject$1> arg0,
    int arg1,
  ) {
    return _PyTuple_GetItem(arg0, arg1);
  }

  late final _PyTuple_GetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<imp$1.PyObject$1> Function(
            ffi.Pointer<imp$1.PyObject$1>,
            Py_ssize_t,
          )
        >
      >('PyTuple_GetItem');
  late final _PyTuple_GetItem =
      _PyTuple_GetItemPtr.asFunction<
        ffi.Pointer<imp$1.PyObject$1> Function(
          ffi.Pointer<imp$1.PyObject$1>,
          int,
        )
      >();

  ffi.Pointer<imp$1.PyObject$1> PyTuple_New(int size) {
    return _PyTuple_New(size);
  }

  late final _PyTuple_NewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<imp$1.PyObject$1> Function(Py_ssize_t)>
      >('PyTuple_New');
  late final _PyTuple_New =
      _PyTuple_NewPtr.asFunction<ffi.Pointer<imp$1.PyObject$1> Function(int)>();

  int PyTuple_SetItem(
    ffi.Pointer<imp$1.PyObject$1> arg0,
    int arg1,
    ffi.Pointer<imp$1.PyObject$1> arg2,
  ) {
    return _PyTuple_SetItem(arg0, arg1, arg2);
  }

  late final _PyTuple_SetItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<imp$1.PyObject$1>,
            Py_ssize_t,
            ffi.Pointer<imp$1.PyObject$1>,
          )
        >
      >('PyTuple_SetItem');
  late final _PyTuple_SetItem =
      _PyTuple_SetItemPtr.asFunction<
        int Function(
          ffi.Pointer<imp$1.PyObject$1>,
          int,
          ffi.Pointer<imp$1.PyObject$1>,
        )
      >();

  int PyTuple_Size(ffi.Pointer<imp$1.PyObject$1> arg0) {
    return _PyTuple_Size(arg0);
  }

  late final _PyTuple_SizePtr =
      _lookup<
        ffi.NativeFunction<Py_ssize_t Function(ffi.Pointer<imp$1.PyObject$1>)>
      >('PyTuple_Size');
  late final _PyTuple_Size =
      _PyTuple_SizePtr.asFunction<
        int Function(ffi.Pointer<imp$1.PyObject$1>)
      >();

  imp$1.PyStatus Py_InitializeFromConfig(ffi.Pointer<PyConfig> config) {
    return _Py_InitializeFromConfig(config);
  }

  late final _Py_InitializeFromConfigPtr =
      _lookup<
        ffi.NativeFunction<imp$1.PyStatus Function(ffi.Pointer<PyConfig>)>
      >('Py_InitializeFromConfig');
  late final _Py_InitializeFromConfig =
      _Py_InitializeFromConfigPtr.asFunction<
        imp$1.PyStatus Function(ffi.Pointer<PyConfig>)
      >();
}

final class PyConfig extends ffi.Struct {
  @ffi.Int()
  external int _config_init;

  @ffi.Int()
  external int isolated;

  @ffi.Int()
  external int use_environment;

  @ffi.Int()
  external int dev_mode;

  @ffi.Int()
  external int install_signal_handlers;

  @ffi.Int()
  external int use_hash_seed;

  @ffi.UnsignedLong()
  external int hash_seed;

  @ffi.Int()
  external int faulthandler;

  @ffi.Int()
  external int tracemalloc;

  @ffi.Int()
  external int import_time;

  @ffi.Int()
  external int code_debug_ranges;

  @ffi.Int()
  external int show_ref_count;

  @ffi.Int()
  external int dump_refs;

  external ffi.Pointer<ffi.WChar> dump_refs_file;

  @ffi.Int()
  external int malloc_stats;

  external ffi.Pointer<ffi.WChar> filesystem_encoding;

  external ffi.Pointer<ffi.WChar> filesystem_errors;

  external ffi.Pointer<ffi.WChar> pycache_prefix;

  @ffi.Int()
  external int parse_argv;

  external PyWideStringList orig_argv;

  external PyWideStringList argv;

  external PyWideStringList xoptions;

  external PyWideStringList warnoptions;

  @ffi.Int()
  external int site_import;

  @ffi.Int()
  external int bytes_warning;

  @ffi.Int()
  external int warn_default_encoding;

  @ffi.Int()
  external int inspect;

  @ffi.Int()
  external int interactive;

  @ffi.Int()
  external int optimization_level;

  @ffi.Int()
  external int parser_debug;

  @ffi.Int()
  external int write_bytecode;

  @ffi.Int()
  external int verbose;

  @ffi.Int()
  external int quiet;

  @ffi.Int()
  external int user_site_directory;

  @ffi.Int()
  external int configure_c_stdio;

  @ffi.Int()
  external int buffered_stdio;

  external ffi.Pointer<ffi.WChar> stdio_encoding;

  external ffi.Pointer<ffi.WChar> stdio_errors;

  @ffi.Int()
  external int legacy_windows_stdio;

  external ffi.Pointer<ffi.WChar> check_hash_pycs_mode;

  @ffi.Int()
  external int use_frozen_modules;

  @ffi.Int()
  external int safe_path;

  @ffi.Int()
  external int pathconfig_warnings;

  external ffi.Pointer<ffi.WChar> program_name;

  external ffi.Pointer<ffi.WChar> pythonpath_env;

  external ffi.Pointer<ffi.WChar> home;

  external ffi.Pointer<ffi.WChar> platlibdir;

  @ffi.Int()
  external int module_search_paths_set;

  external PyWideStringList module_search_paths;

  external ffi.Pointer<ffi.WChar> stdlib_dir;

  external ffi.Pointer<ffi.WChar> executable;

  external ffi.Pointer<ffi.WChar> base_executable;

  external ffi.Pointer<ffi.WChar> prefix;

  external ffi.Pointer<ffi.WChar> base_prefix;

  external ffi.Pointer<ffi.WChar> exec_prefix;

  external ffi.Pointer<ffi.WChar> base_exec_prefix;

  @ffi.Int()
  external int skip_source_first_line;

  external ffi.Pointer<ffi.WChar> run_command;

  external ffi.Pointer<ffi.WChar> run_module;

  external ffi.Pointer<ffi.WChar> run_filename;

  @ffi.Int()
  external int _install_importlib;

  @ffi.Int()
  external int _init_main;

  @ffi.Int()
  external int _isolated_interpreter;

  @ffi.Int()
  external int _is_python_build;
}

final class PyWideStringList extends ffi.Struct {
  @Py_ssize_t()
  external int length;

  external ffi.Pointer<ffi.Pointer<ffi.WChar>> items;

  static ffi.Pointer<PyWideStringList> $allocate(
    ffi.Allocator $allocator, {
    required int length,
    required ffi.Pointer<ffi.Pointer<ffi.WChar>> items,
  }) => $allocator<PyWideStringList>()
    ..ref.length = length
    ..ref.items = items;
}

typedef Py_ssize_t = ffi.LongLong;
typedef DartPy_ssize_t = int;
