// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Adds the value pointed to by [value]. Its native type must match [type].
@ffi.Native<ffi.Bool Function(Handle, ffi.Pointer<ffi.Void>)>()
external bool accumulator_add(int handle, ffi.Pointer<ffi.Void> value);

/// Creates an accumulator whose concrete C++ type is selected at runtime.
/// Returns 0 when [type] is unsupported.
@ffi.Native<Handle Function(ValueType_t)>()
external int accumulator_create(int type);

/// Releases the type-erased adapter and its concrete template instance.
@ffi.Native<ffi.Void Function(Handle)>()
external void accumulator_dispose(int handle);

/// Copies the current value into [output]. Its native type must match [type].
@ffi.Native<ffi.Bool Function(Handle, ffi.Pointer<ffi.Void>)>()
external bool accumulator_get(int handle, ffi.Pointer<ffi.Void> output);

typedef Handle = ffi.UintPtr;
typedef DartHandle = int;

enum ValueType {
  INT32(1),
  DOUBLE(2);

  final int value;
  const ValueType(this.value);

  static ValueType fromValue(int value) => switch (value) {
    1 => INT32,
    2 => DOUBLE,
    _ => throw ArgumentError('Unknown value for ValueType: $value'),
  };
}

typedef ValueType_t = ffi.Int32;
typedef DartValueType_t = int;
